version: '3.1'

services:
  v2fly:
    image: v2fly/v2fly-core
    restart: always
    network_mode: "bridge"
    container_name: v2fly
    ports:
      - "10086:10086"
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json