version: '3.1'

services:
  v2ray:
    image: v2fly/v2fly-core
    restart: always
    hostname: v2ray
    container_name: v2ray
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json